parameters:
  secret_management:
    vault_addr: https://vault.example.com
    vault_role: syn-cluster

  argocd:
    monitoring:
      enabled: false

  commodore:
    jsonnet_libs:
      - name: kube-libsonnet
        repository: https://github.com/bitnami-labs/kube-libsonnet
        files:
          - libfile: kube.libsonnet
            targetfile: kube.libjsonnet

  kapitan:
    vars:
      namespace: cluster
    secrets:
      vaultkv:
        VAULT_ADDR: ${secret_management:vault_addr}
        VAULT_SKIP_VERIFY: 'false'
        VAULT_CAPATH: /etc/ssl/certs/
        auth: token
        engine: kv-v2
        mount: clusters/kv

  steward:
    api_url: http://lieutenant.172-18-0-2.nip.io

  components:
    argocd:
      url: https://github.com/projectsyn/component-argocd.git
    metrics-server:
      url: https://github.com/projectsyn/component-metrics-server.git
